import { describe, it, expect } from 'vitest';
import { OK, NOT_FOUND, UNSUPPORTED, STALE, EVALUATION_FAILED, buildSnapshotJs, buildValidateJs, buildPointerJs, parseResult, evalParsed } from '../src/human/stealthDom.js';

type E = any;
function node(tag:string, text='', cls=''):E { const e:any={tagName:tag.toUpperCase(),nodeType:1,childNodes:[],children:[],parentElement:null,previousElementSibling:null,textContent:text,isConnected:true,disabled:false,readOnly:false,isContentEditable:false,type:'text',value:'',attrs:{},checked:false}; if(text)e.childNodes.push({nodeType:3,nodeValue:text}); e.getAttribute=(n:string)=>e.attrs[n]??null;e.hasAttribute=(n:string)=>n in e.attrs;e.contains=(x:E)=>x===e||e.children.some((c:E)=>c.contains(x));e.closest=()=>null;e.getRootNode=()=>e.parentElement?e.parentElement.getRootNode():doc;e.getBoundingClientRect=()=>({x:1,y:2,width:10,height:10});e.matches=(s:string)=>s==='*'||s.split('.').every((x,i)=>i?cls.split(' ').includes(x):!x||x===tag);return e; }
let doc:any;
function append(p:E,c:E){c.parentElement=p;c.previousElementSibling=p.children.at(-1)??null;p.children.push(c);p.childNodes.push(c);}
function run(js:string, roots:E[], point?:E, active?:E){doc={children:roots,head:{contains:()=>false},activeElement:active??null,querySelectorAll:()=>[],elementFromPoint:()=>point??null,evaluate:()=>({snapshotLength:0,snapshotItem:()=>null})}; for(const r of roots)r.getRootNode=()=>doc; const f=new Function('document','XPathResult','getComputedStyle','globalThis','return '+js);return f(doc,{ORDERED_NODE_SNAPSHOT_TYPE:7},()=>({display:'block',visibility:'visible'}),{});}

describe('protocol',()=>{it('strictly rejects malformed payloads and evaluator failures',async()=>{expect(parseResult({v:1,r:OK,targetId:1})).toMatchObject({status:OK});for(const x of [null,{}, {v:2,r:OK,targetId:1},{v:1,r:OK},{v:1,r:STALE,targetId:1.5}])expect(parseResult(x)).toEqual({status:EVALUATION_FAILED});expect(parseResult({v:1,r:NOT_FOUND})).toEqual({status:NOT_FOUND});expect(parseResult({v:1,r:UNSUPPORTED})).toEqual({status:UNSUPPORTED});expect(await evalParsed({evaluate:async()=>{throw Error()}},'x')).toEqual({status:EVALUATION_FAILED});});});

describe('shipped resolver',()=>{it('executes descendant, child, adjacent, sibling, lists and structural has-text',()=>{const root=node('div');const a=node('span','one','a'), b=node('button','Save','b'), c=node('button','Other','c');append(root,a);append(root,b);append(root,c);for(const s of ['div button','div > button','.a + button','.a ~ button','.no, button:has-text("Save")'])expect(run(buildSnapshotJs(s),[root]).r).toBe(OK);});it('executes exact/lax/regex text and excludes script text (#512)',()=>{const r=node('div'), s=node('span',' Hello   World '), script=node('script','secret');append(r,s);append(r,script);expect(run(buildSnapshotJs('text="Hello World"'),[r]).r).toBe(OK);expect(run(buildSnapshotJs('text=hello world'),[r]).r).toBe(OK);expect(run(buildSnapshotJs('text=/world/i'),[r]).r).toBe(OK);expect(run(buildSnapshotJs('text=secret'),[r]).r).toBe(NOT_FOUND);});it('executes native and ARIA state',()=>{const root=node('div'),disabled=node('button','','disabled'),ariaDisabled=node('button','','aria-disabled'),readonly=node('div','','readonly');disabled.attrs.disabled='';ariaDisabled.attrs.role='button';ariaDisabled.attrs['aria-disabled']='true';readonly.attrs.role='textbox';readonly.attrs['aria-readonly']='true';append(root,disabled);append(root,ariaDisabled);append(root,readonly);expect(run(buildSnapshotJs('.disabled'),[root]).enabled).toBe(false);expect(run(buildSnapshotJs('.aria-disabled'),[root]).enabled).toBe(false);expect(run(buildSnapshotJs('.readonly'),[root]).editable).toBe(false);});it('executes deep shadow ordering, focus, hit testing and stale validation',()=>{const host=node('div'), light=node('button','light'), shadow=node('button','shadow');append(host,light);const disabled=node('button');disabled.attrs.disabled='';append(host,disabled);host.shadowRoot={children:[shadow],elementFromPoint:()=>shadow,activeElement:shadow};shadow.getRootNode=()=>host.shadowRoot;shadow.parentElement=null;expect(run(buildSnapshotJs('button >> nth=2'),[host],host,host).focused).toBe(true);expect(run(buildSnapshotJs('button >> nth=1'),[host]).enabled).toBe(false);expect(run(buildSnapshotJs('button'),[host],host,host).focused).toBe(false);expect(run(buildPointerJs('button >> nth=2',1,2),[host],host).hit).toBe(true);expect(run(buildValidateJs('button',999,1,2),[host]).r).toBe(STALE);});});
